### ISSUE TITLE
Compile error on raspberry pi 4 kernel 5.15

### ISSUE THREAD

**Issue by RonGroen** [niosHD/xr_usb_serial_common-1c#2]
am using https://github.com/niosHD/xr_usb_serial_common-1c
together with a Raspberry Pi 4 with succes.

Now I installed a new version and don't get is make any more.

Looking on the internet I found.
-----------------
With kernel v5.15, put_tty_driver has been replaced with tty_driver_kref_put. Please build with this patch: #152
https://github.com/xmm7360/xmm7360-pci/issues/150

Error report:
make clean
rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions vtty Module.symvers modules.order
root@raspberrypi:/usr/src/xr_usb_serial_common-1c-master# make 
make -C /lib/modules/5.15.32-v7l+/build M=/usr/src/xr_usb_serial_common-1c-master
make[1]: Entering directory '/usr/src/linux-headers-5.15.32-v7l+'
  CC [M]  /usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.o
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c: In function ‘xr_usb_serial_tty_ioctl’:
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:917:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  917 |                 if (get_user(reg, (int __user *)(arg + sizeof(int))))
      |                 ^~
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:920:11: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  920 |           if (channel == -1)
      |           ^~
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:946:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  946 |                 if (get_user(val, (int __user *)(arg + 2 * sizeof(int))))
      |                 ^~
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:949:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  949 |    if (channel == -1)
      |    ^~
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c: In function ‘xr_usb_serial_suspend’:
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1731:15: error: ‘ASYNCB_INITIALIZED’ undeclared (first use in this function); did you mean ‘RCU_INITIALIZER’?
 1731 |  if (test_bit(ASYNCB_INITIALIZED, &xr_usb_serial->port.flags))
      |               ^~~~~~~~~~~~~~~~~~
      |               RCU_INITIALIZER
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1731:15: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c: In function ‘xr_usb_serial_resume’:
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1752:15: error: ‘ASYNCB_INITIALIZED’ undeclared (first use in this function); did you mean ‘RCU_INITIALIZER’?
 1752 |  if (test_bit(ASYNCB_INITIALIZED, &xr_usb_serial->port.flags)) {

......................
.............
 1868 |  xr_usb_serial_tty_driver = alloc_tty_driver(XR_USB_SERIAL_TTY_MINORS);
      |                             ^~~~~~~~~~~~~~~~
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1868:27: warning: assignment to ‘struct tty_driver *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 1868 |  xr_usb_serial_tty_driver = alloc_tty_driver(XR_USB_SERIAL_TTY_MINORS);
      |                           ^
/usr/src/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1885:3: error: implicit declaration of function ‘put_tty_driver’ [-Werror=implicit-function-declaration]
 1885 |   put_tty_driver(xr_usb_serial_tty_driver);
      |   ^~~~~~~~~~~~~~

**Comment by RonGroen** [comment]
It can be solved by applying the patch on the other issue. But can't  this be added to the linux kernel? That will save a lot of people a lot of time. (or a fail)

But upgrading to 5.15 gives the error again:
/xr_usb_serial_common-1c-master/xr_usb_serial_common.c:1871:29: error: implicit declaration of function ‘alloc_tty_driver’ [-Werror=implicit-function-declaration]
 1871 |  xr_usb_serial_tty_driver = alloc_tty_driver(XR_USB_SERIAL_TTY_MINORS);
      |                             ^~~~~~~~~~~~~~~~
and more.....

**Comment by RonGroen** [comment]
Problem solved. I sent the updated code to the original contributer to update github.

**Comment by niosHD** [comment]
Hi, thanks for letting me know of the issue and the pointers to fixes, I will try to integrate them when I have time. I don't think that I will be able to test the module with the changes though because I don't have access to the Pi that I use this module on.

**Comment by niosHD** [comment]
The code compiles now again with newer kernel versions (tested with 5.17).
